export const MOCK_X_STORIES = [
  {
    id: 'x-1',
    title: 'Interception over Tehran reported by local channels',
    summary: 'Air defense units engaged incoming projectiles over Tehran outskirts.',
    category: 'interception',
    severity: 3,
    source_name: 'X Monitor Desk',
    source_url: 'https://x.com/example/status/1',
    published_at: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    location_name: 'Tehran',
    tags: ['iran', 'air-defense'],
  },
  {
    id: 'x-2',
    title: 'Missile launch alert near western Iran corridor',
    summary: 'Suspected launch activity tracked by regional observers.',
    category: 'missile_launch',
    severity: 4,
    source_name: 'Open Source Channel',
    source_url: 'https://x.com/example/status/2',
    published_at: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    location_name: 'Isfahan',
    tags: ['missile', 'iran'],
  },
  {
    id: 'tg-1',
    dedupe_key: 'warmonitors:1001',
    source_type: 'telegram',
    source_name: 'War Monitor',
    source_handle: 'warmonitors',
    title: 'Drone activity reported near Hormuz shipping lane',
    body_text: 'Reports of drone activity near Hormuz and tanker transit warnings.',
    summary: 'Reports of drone activity near Hormuz and tanker transit warnings.',
    category: 'telegram_alert',
    severity: 4,
    source_url: 'https://t.me/warmonitors/1001',
    canonical_url: 'https://t.me/warmonitors/1001',
    published_at: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    location_name: 'Strait of Hormuz',
    latitude: 26.566,
    longitude: 56.249,
    confidence: 'high',
    tags: ['hormuz', 'tanker', 'drone'],
  },
  {
    id: 'x-expired',
    title: 'Older strike event (should expire)',
    summary: 'This should not render after rolling-window filter.',
    category: 'strike',
    severity: 4,
    source_name: 'Archive',
    source_url: 'https://x.com/example/status/5',
    published_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    location_name: 'Israel',
    tags: ['expired'],
  },
];

export const MOCK_MARKETS = {
  brent: { symbol: 'BRENT', value: 86.42, delta: +0.78, updated_at: new Date().toISOString() },
  wti: { symbol: 'WTI', value: 82.11, delta: -0.34, updated_at: new Date().toISOString() },
  polymarket: {
    label: 'OIL ABOVE $100',
    yes: 0.31,
    no: 0.69,
    updated_at: new Date().toISOString(),
  },
};
